GET http://localhost:9876/api/matches


###
POST http://localhost:9876/api/matches
Content-Type: application/json

{
  "memo":"test1",
  "summary":"test2",
  "winner1Name":"mini",
  "winner1Location":"3",
  "winner1Race":"Z",
  "winner1AbilityId":1,
  "winner2Name":"effort",
  "winner2Location":"6",
  "winner2Race":"P",
  "winner2AbilityId":2,
  "loser1Name":"organ",
  "loser1Location":"12",
  "loser1Race":"T",
  "loser1AbilityId":4,
  "loser2Name":"ggaemo",
  "loser2Location":"9",
  "loser2Race":"Z",
  "loser2AbilityId":5
}

###

PUT http://localhost:9876/api/abilities/160
Content-Type: application/json

{
"id": 160,
  "abilityname": "PUT으로 능력 업데이트",
  "explanation": "update된 능력",
  "removed": false
}

###
DELETE http://localhost:9876/api/abilities/160